-- Execute in Supabase SQL Editor. The anon client only needs INSERT on contact_messages
-- and SELECT on portfolio_experience; enable RLS before going to production.
create table if not exists public.contact_messages (
  id uuid primary key default gen_random_uuid(), name text not null,
  email text not null, message text not null, created_at timestamptz not null default now()
);
create table if not exists public.portfolio_experience (
  id bigint generated by default as identity primary key, locale text not null check (locale in ('pt','en')),
  company text not null, year text not null, current boolean not null default false,
  position text not null, period text not null, location text not null,
  description text not null, tags text[] not null default '{}', sort_order integer not null default 0
);
alter table public.contact_messages enable row level security;
alter table public.portfolio_experience enable row level security;
create policy "public can send contact messages" on public.contact_messages for insert to anon with check (true);
create policy "public can read published experience" on public.portfolio_experience for select to anon using (true);
-- Optional: add an anti-spam/rate-limit Edge Function before exposing this publicly.
