-- Execute after schema.sql. Safe to run repeatedly for this initial dataset only after
-- clearing the table; review/edit content before publishing.
truncate table public.portfolio_experience restart identity;

insert into public.portfolio_experience
(locale, company, year, current, position, period, location, description, tags, sort_order)
values
('pt','Meutudo','2023',true,'Desenvolvedor Front-end Sênior','Jul 2023 — Presente','Remoto', $$Soluções mobile para o setor financeiro (React Native, TypeScript, Redux, Jest, RTL); fluxos transacionais do Consignado Privado CLT (900 mil+ usuários, R$ 1,57 bi+ em 2025); liderança técnica dos fluxos de autorização/validação de cartão do Pix Parcelado (BaaS Dock); idealização de plataforma de geração dinâmica de telas via protocolo MCP do Figma + APIs da Anthropic (Claude) para UI aderente a design tokens e guard rails; arquitetura de atualização de telas em tempo real sem publicação em loja.$$ , array['React Native','TypeScript','Redux','Jest','MCP','Claude API'], 1),
('pt','HX-TOS (ex-Hexagon Pro)','2021',false,'Team Lead / Dev Front-end','Fev 2021 — Jul 2023','Santos, SP', $$Liderança de 6 devs em ecossistema com 12+ soluções logísticas (Porto de Santos); migração de Angular 6 para React (TypeScript, Vite, Tailwind, RTL, Cypress); mentoria e code review; representação da empresa no Web Summit Lisboa 2022.$$ , array['React','TypeScript','Vite','Tailwind CSS','Cypress'], 2),
('pt','Mosten (ex-ModalGR)','2020',false,'Consultor / Dev Front-end','Out 2020 — Fev 2021','Santos, SP', $$Plataforma para construção civil (React, styled-components, Materialize); Figma → produção; projeto que originou a startup Hexagon Pro (depois HX-TOS, selecionada pelo Cubo Itaú).$$ , array['React','styled-components','Figma'], 3),
('pt','Loocal','2020',false,'Consultor de Front-end','Jul — Out 2020','Santos, SP', $$Backoffice de entregas (Next.js, styled-components); integração em tempo real; operação presente em 30+ municípios, 1 milhão+ de entregas.$$ , array['Next.js','styled-components'], 4),
('pt','Goflux','2019',false,'Dev Front-end','Dez 2019 — Jul 2020','São Paulo, SP', $$Único dev front-end da equipe mobile (React Native, Redux); app de monitoramento de motoristas com geolocalização; portal de leilão de frete.$$ , array['React Native','Redux'], 5),
('pt','Mosten (ex-ModalGR)','2018',false,'Estagiário → Jr → Pleno','Jul 2018 — Dez 2019','Santos, SP', $$Angular/AngularJS/Python; sistema de monitoramento para o Porto de Santos; app hospitalar com 20 mil+ downloads; mentoria técnica.$$ , array['Angular','Python'], 6),

('en','Meutudo','2023',true,'Senior Front-end Developer','Jul 2023 — Present','Remote', $$Mobile solutions for the financial sector (React Native, TypeScript, Redux, Jest, RTL); transactional flows for the Private Payroll Loan (900k+ users, R$ 1.57bn+ in 2025); technical leadership of the card authorization/validation flows for Pix Installments (Dock BaaS); conceived a platform for dynamic screen generation using Figma’s MCP protocol + Anthropic (Claude) APIs for UI compliant with design tokens and guard rails; architecture for real-time screen updates without store releases.$$ , array['React Native','TypeScript','Redux','Jest','MCP','Claude API'], 1),
('en','HX-TOS (ex-Hexagon Pro)','2021',false,'Team Lead / Front-end Dev','Feb 2021 — Jul 2023','Santos, SP', $$Led 6 devs across an ecosystem of 12+ logistics solutions (Port of Santos); migrated Angular 6 to React (TypeScript, Vite, Tailwind, RTL, Cypress); mentoring and code review; represented the company at Web Summit Lisbon 2022.$$ , array['React','TypeScript','Vite','Tailwind CSS','Cypress'], 2),
('en','Mosten (ex-ModalGR)','2020',false,'Consultant / Front-end Dev','Oct 2020 — Feb 2021','Santos, SP', $$Platform for the construction industry (React, styled-components, Materialize); Figma → production; the project that originated the startup Hexagon Pro (later HX-TOS, selected by Cubo Itaú).$$ , array['React','styled-components','Figma'], 3),
('en','Loocal','2020',false,'Front-end Consultant','Jul — Oct 2020','Santos, SP', $$Delivery backoffice (Next.js, styled-components); real-time integration; operation across 30+ municipalities, 1 million+ deliveries.$$ , array['Next.js','styled-components'], 4),
('en','Goflux','2019',false,'Front-end Dev','Dec 2019 — Jul 2020','São Paulo, SP', $$Sole front-end dev on the mobile team (React Native, Redux); driver monitoring app with geolocation; freight auction portal.$$ , array['React Native','Redux'], 5),
('en','Mosten (ex-ModalGR)','2018',false,'Intern → Jr → Mid-level','Jul 2018 — Dec 2019','Santos, SP', $$Angular/AngularJS/Python; monitoring system for the Port of Santos; healthcare app with 20k+ downloads; technical mentoring.$$ , array['Angular','Python'], 6);
